# Generated by Django 6.0.2 on 2026-02-07 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('is_dangerous', models.BooleanField(db_index=True, default=False)),
                ('danger_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('horizontal_speed_mps', models.FloatField(blank=True, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='drones.drone')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['drone', 'timestamp'], name='drones_dron_drone_i_e324e4_idx')],
            },
        ),
    ]
